-- Baseline del esquema del CMS (generado con pg_dump 16, schema-only, sin owner/privilegios).
-- En el servidor NO se ejecuta (baseline-on-migrate lo marca); sirve para levantar un entorno
-- Postgres nuevo. Las migraciones futuras van como V2__, V3__, ...
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: audit_logs_no_modify(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.audit_logs_no_modify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs es de solo inserción: % no permitido (PCI DSS 10.5 tamper-prevention)', TG_OP;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255),
    entity_id character varying(255),
    entity_name character varying(255),
    "timestamp" timestamp(6) without time zone,
    username character varying(255),
    prev_hash character varying(64),
    record_hash character varying(64)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authorization_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authorization_attempts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19,2) NOT NULL,
    approval_code character varying(40),
    approved boolean NOT NULL,
    channel character varying(20),
    country_code character varying(3),
    merchant_id character varying(50),
    merchant_name character varying(100),
    response_code character varying(4) NOT NULL,
    risk_reasons character varying(500),
    risk_score integer NOT NULL,
    step_up boolean NOT NULL,
    card_id bigint NOT NULL
);


--
-- Name: authorization_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authorization_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authorization_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authorization_holds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authorization_holds (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    acquirer_id character varying(11),
    amount numeric(19,2) NOT NULL,
    approval_code character varying(40) NOT NULL,
    capture_ref character varying(80),
    captured_amount numeric(19,2),
    expires_at timestamp(6) without time zone,
    external_ref character varying(80),
    idempotency_key character varying(120),
    merchant_id character varying(50),
    merchant_name character varying(100),
    network_advice boolean DEFAULT false NOT NULL,
    rrn character varying(12),
    stan character varying(6),
    stand_in boolean DEFAULT false NOT NULL,
    stand_in_pending boolean DEFAULT false NOT NULL,
    stand_in_settled_at timestamp(6) without time zone,
    status character varying(16) NOT NULL,
    transaction_type character varying(30),
    card_id bigint NOT NULL,
    CONSTRAINT authorization_holds_status_check CHECK (((status)::text = ANY ((ARRAY['HELD'::character varying, 'CAPTURED'::character varying, 'RELEASED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: authorization_holds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authorization_holds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authorization_holds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_controls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_controls (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    atm_enabled boolean NOT NULL,
    contactless_enabled boolean NOT NULL,
    daily_limit numeric(19,2),
    ecommerce_enabled boolean NOT NULL,
    international_enabled boolean NOT NULL,
    monthly_limit numeric(19,2),
    per_transaction_max numeric(19,2),
    pos_enabled boolean NOT NULL,
    travel_notice_until date,
    weekly_limit numeric(19,2),
    card_id bigint NOT NULL
);


--
-- Name: card_controls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_controls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_controls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_products (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    annual_interest_rate numeric(5,2),
    atm_withdrawal_fee_fixed numeric(19,2),
    atm_withdrawal_fee_percent numeric(5,2),
    bin character varying(255) NOT NULL,
    card_color text,
    card_type character varying(255) NOT NULL,
    country character varying(255),
    credit_limit numeric(19,2),
    currency character varying(255) NOT NULL,
    cvk_index character varying(255),
    daily_limit numeric(19,2),
    hsm_algorithm character varying(255),
    inactivity_fee numeric(19,2),
    international_tx_fee_percent numeric(5,2),
    issuance_fee numeric(19,2),
    late_payment_fee numeric(19,2),
    logo_url text,
    monthly_limit numeric(19,2),
    monthly_maintenance_fee numeric(19,2),
    network character varying(255) NOT NULL,
    payment_type character varying(255) NOT NULL,
    pin_block_format character varying(255),
    product_code character varying(255) NOT NULL,
    product_name character varying(255) NOT NULL,
    pvk_index character varying(255),
    replacement_fee numeric(19,2),
    weekly_limit numeric(19,2),
    CONSTRAINT card_products_card_type_check CHECK (((card_type)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying, 'PREPAID'::character varying])::text[]))),
    CONSTRAINT card_products_network_check CHECK (((network)::text = ANY ((ARRAY['VISA'::character varying, 'MASTERCARD'::character varying, 'ALODIGA_PRIVATE'::character varying])::text[]))),
    CONSTRAINT card_products_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['PREPAID'::character varying, 'POSTPAID'::character varying])::text[])))
);


--
-- Name: card_products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cards (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    card_category character varying(255),
    credit_limit numeric(19,2),
    crypto_provisioned_at timestamp(6) without time zone,
    embossed_name character varying(255),
    expiry_date date,
    external_account_id character varying(80),
    last4 character varying(255),
    pan_encrypted character varying(120),
    pan_hash character varying(64),
    pan_sequence character varying(2),
    pvki character varying(1),
    pvv character varying(4),
    service_code character varying(3),
    status character varying(255),
    customer_id bigint NOT NULL,
    product_id bigint,
    CONSTRAINT cards_card_category_check CHECK (((card_category)::text = ANY ((ARRAY['PHYSICAL'::character varying, 'VIRTUAL'::character varying])::text[]))),
    CONSTRAINT cards_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ACTIVE'::character varying, 'BLOCKED'::character varying, 'EXPIRED'::character varying, 'CANCELED'::character varying, 'SUSPENDED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clearing_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clearing_batches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    chargebacks_amount numeric(19,2) NOT NULL,
    content text,
    cycle_date date NOT NULL,
    error character varying(500),
    exception_count integer NOT NULL,
    fees_amount numeric(19,2) NOT NULL,
    file_id character varying(60),
    file_name character varying(160) NOT NULL,
    interchange_amount numeric(19,2),
    loaded_by character varying(80),
    matched_count integer NOT NULL,
    network character varying(20) NOT NULL,
    presentments_amount numeric(19,2) NOT NULL,
    presentments_count integer NOT NULL,
    processed_at timestamp(6) without time zone,
    record_count integer NOT NULL,
    reversals_amount numeric(19,2) NOT NULL,
    settlement_cycle_id bigint,
    sha256 character varying(64) NOT NULL,
    status character varying(12) NOT NULL,
    trailer_amount numeric(19,2),
    trailer_count integer,
    CONSTRAINT clearing_batches_network_check CHECK (((network)::text = ANY ((ARRAY['VISA'::character varying, 'MASTERCARD'::character varying, 'DOMESTIC'::character varying])::text[]))),
    CONSTRAINT clearing_batches_status_check CHECK (((status)::text = ANY ((ARRAY['LOADED'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: clearing_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clearing_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clearing_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clearing_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clearing_records (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19,2) NOT NULL,
    approval_code character varying(40),
    approval_id character varying(6),
    card_id bigint,
    currency character varying(3),
    detail character varying(400),
    interchange_fee numeric(19,2),
    line_no integer NOT NULL,
    mcc character varying(4),
    merchant_id character varying(50),
    merchant_name character varying(120),
    outcome character varying(20),
    pan_masked character varying(24),
    reason_code character varying(10),
    rrn character varying(12),
    stan character varying(6),
    transaction_date date,
    type character varying(16) NOT NULL,
    batch_id bigint NOT NULL,
    CONSTRAINT clearing_records_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['MATCHED_CAPTURED'::character varying, 'AMOUNT_MISMATCH'::character varying, 'ALREADY_CAPTURED'::character varying, 'FORCE_POSTED'::character varying, 'NO_CARD'::character varying, 'REVERSED'::character varying, 'DISPUTE_LINKED'::character varying, 'FEE_BOOKED'::character varying, 'UNMATCHED'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT clearing_records_type_check CHECK (((type)::text = ANY ((ARRAY['PRESENTMENT'::character varying, 'REVERSAL'::character varying, 'CHARGEBACK'::character varying, 'REPRESENTMENT'::character varying, 'FEE'::character varying])::text[])))
);


--
-- Name: clearing_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clearing_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clearing_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    external_client_id character varying(80),
    full_name character varying(255),
    phone_number character varying(255),
    address_line character varying(160),
    birth_date date,
    curp character varying(18),
    email character varying(120),
    first_names character varying(120),
    maternal_surname character varying(80),
    nationality character varying(40),
    occupation character varying(80),
    paternal_surname character varying(80),
    pep boolean DEFAULT false NOT NULL,
    postal_code character varying(10),
    rfc character varying(13),
    sex character varying(1),
    state character varying(40)
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dispute_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dispute_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action character varying(40) NOT NULL,
    from_status character varying(24),
    note character varying(500),
    performed_by character varying(80),
    to_status character varying(24),
    dispute_id bigint NOT NULL,
    CONSTRAINT dispute_events_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['OPENED'::character varying, 'CHARGEBACK_SENT'::character varying, 'REPRESENTED'::character varying, 'RESOLVED_CUSTOMER'::character varying, 'RESOLVED_MERCHANT'::character varying, 'WITHDRAWN'::character varying])::text[]))),
    CONSTRAINT dispute_events_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['OPENED'::character varying, 'CHARGEBACK_SENT'::character varying, 'REPRESENTED'::character varying, 'RESOLVED_CUSTOMER'::character varying, 'RESOLVED_MERCHANT'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: dispute_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dispute_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dispute_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dispute_evidences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dispute_evidences (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    added_by character varying(80),
    content bytea,
    content_type character varying(120),
    description character varying(500),
    filename character varying(255) NOT NULL,
    sha256 character varying(64) NOT NULL,
    size bigint NOT NULL,
    dispute_id bigint NOT NULL
);


--
-- Name: dispute_evidences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dispute_evidences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dispute_evidences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dispute_reasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dispute_reasons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    chargeback_days integer NOT NULL,
    code character varying(12) NOT NULL,
    description character varying(200) NOT NULL,
    network character varying(12) NOT NULL,
    representment_days integer NOT NULL,
    requires_evidence boolean NOT NULL,
    resolve_days integer NOT NULL
);


--
-- Name: dispute_reasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dispute_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dispute_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: disputes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.disputes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    acquirer_case_ref character varying(80),
    amount numeric(19,2) NOT NULL,
    approval_code character varying(40) NOT NULL,
    chargeback_deadline date,
    chargeback_sent_at timestamp(6) without time zone,
    credit_ref character varying(80),
    credit_reversal_ref character varying(80),
    currency character varying(3),
    deadline_breached boolean NOT NULL,
    description character varying(1000),
    opened_by character varying(80),
    outcome character varying(16),
    provisional_credit boolean NOT NULL,
    represented_at timestamp(6) without time zone,
    representment_deadline date,
    resolution_note character varying(500),
    resolve_by date,
    resolved_at timestamp(6) without time zone,
    status character varying(24) NOT NULL,
    transaction_date date,
    card_id bigint NOT NULL,
    hold_id bigint,
    reason_id bigint NOT NULL,
    CONSTRAINT disputes_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'MERCHANT'::character varying])::text[]))),
    CONSTRAINT disputes_status_check CHECK (((status)::text = ANY ((ARRAY['OPENED'::character varying, 'CHARGEBACK_SENT'::character varying, 'REPRESENTED'::character varying, 'RESOLVED_CUSTOMER'::character varying, 'RESOLVED_MERCHANT'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: disputes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.disputes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disputes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fraud_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fraud_alerts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action_taken character varying(40),
    amount numeric(19,2),
    analyst_note character varying(500),
    merchant_id character varying(50),
    merchant_name character varying(100),
    reasons character varying(500),
    reviewed_at timestamp(6) without time zone,
    reviewed_by character varying(80),
    risk_score integer NOT NULL,
    status character varying(16) NOT NULL,
    type character varying(16) NOT NULL,
    card_id bigint,
    CONSTRAINT fraud_alerts_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED'::character varying, 'DISMISSED'::character varying])::text[]))),
    CONSTRAINT fraud_alerts_type_check CHECK (((type)::text = ANY ((ARRAY['DECLINED'::character varying, 'STEP_UP'::character varying, 'ENUMERATION'::character varying])::text[])))
);


--
-- Name: fraud_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fraud_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fraud_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fraud_blocklist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fraud_blocklist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    added_by character varying(80),
    reason character varying(300),
    source character varying(12) NOT NULL,
    type character varying(16) NOT NULL,
    value character varying(80) NOT NULL,
    CONSTRAINT fraud_blocklist_source_check CHECK (((source)::text = ANY ((ARRAY['INTERNAL'::character varying, 'EXTERNAL'::character varying])::text[]))),
    CONSTRAINT fraud_blocklist_type_check CHECK (((type)::text = ANY ((ARRAY['MERCHANT_ID'::character varying, 'COUNTRY'::character varying, 'CARD'::character varying])::text[])))
);


--
-- Name: fraud_blocklist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fraud_blocklist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fraud_blocklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guild_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guild_alerts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19,2),
    assumed_loss boolean NOT NULL,
    attempts integer NOT NULL,
    auto_action character varying(60),
    bin character varying(8),
    card_id bigint,
    closed_at timestamp(6) without time zone,
    closed_by character varying(80),
    description character varying(1000),
    direction character varying(10) NOT NULL,
    guild_folio character varying(60),
    last4 character varying(4),
    last_error character varying(500),
    merchant_id character varying(50),
    merchant_name character varying(120),
    raised_by character varying(80),
    received_at timestamp(6) without time zone,
    resolution character varying(500),
    respond_by date,
    sent_at timestamp(6) without time zone,
    source_ref character varying(60),
    status character varying(15) NOT NULL,
    type character varying(30) NOT NULL,
    CONSTRAINT guild_alerts_direction_check CHECK (((direction)::text = ANY ((ARRAY['OUTBOUND'::character varying, 'INBOUND'::character varying])::text[]))),
    CONSTRAINT guild_alerts_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_SEND'::character varying, 'SENT'::character varying, 'FAILED'::character varying, 'RECEIVED'::character varying, 'IN_REVIEW'::character varying, 'CLOSED'::character varying, 'EXPIRED'::character varying])::text[]))),
    CONSTRAINT guild_alerts_type_check CHECK (((type)::text = ANY ((ARRAY['ENUMERATION'::character varying, 'CONFIRMED_FRAUD'::character varying, 'COMPROMISED_CARD'::character varying, 'SUSPICIOUS_MERCHANT'::character varying, 'CHARGEBACK_PREVENTION'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: guild_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guild_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guild_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guild_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guild_verifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    checked_at timestamp(6) without time zone,
    degraded boolean NOT NULL,
    folio character varying(60),
    listed boolean NOT NULL,
    reason character varying(300),
    subject character varying(60) NOT NULL,
    subject_type character varying(10) NOT NULL,
    valid_until timestamp(6) without time zone,
    CONSTRAINT guild_verifications_subject_type_check CHECK (((subject_type)::text = ANY ((ARRAY['CARD'::character varying, 'MERCHANT'::character varying])::text[])))
);


--
-- Name: guild_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guild_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guild_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idempotency_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idempotency_records (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    idempotency_key character varying(255) NOT NULL,
    response_payload text
);


--
-- Name: idempotency_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idempotency_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.idempotency_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kyc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kyc (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    document_number character varying(255),
    document_type character varying(255),
    expires_at timestamp(6) without time zone,
    status character varying(255),
    verified_at timestamp(6) without time zone,
    customer_id bigint NOT NULL,
    checks_json text,
    review_note character varying(500),
    reviewed_at timestamp(6) without time zone,
    reviewed_by character varying(80),
    risk_level character varying(10),
    screened_at timestamp(6) without time zone,
    CONSTRAINT kyc_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REVIEW'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: kyc_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kyc_documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content_encrypted text,
    content_type character varying(80),
    document_type character varying(40),
    extracted_json text,
    file_name character varying(160),
    sha256 character varying(64),
    side character varying(8) NOT NULL,
    size_bytes bigint NOT NULL,
    uploaded_at timestamp(6) without time zone,
    uploaded_by character varying(80),
    verification character varying(16),
    verification_detail character varying(500),
    verified_at timestamp(6) without time zone,
    verified_by character varying(80),
    customer_id bigint NOT NULL,
    CONSTRAINT kyc_documents_side_check CHECK (((side)::text = ANY ((ARRAY['FRONT'::character varying, 'BACK'::character varying])::text[]))),
    CONSTRAINT kyc_documents_verification_check CHECK (((verification)::text = ANY ((ARRAY['PENDING_MANUAL'::character varying, 'UNREADABLE'::character varying, 'MATCH'::character varying, 'MISMATCH'::character varying])::text[])))
);


--
-- Name: kyc_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kyc_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kyc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kyc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ledger_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ledger_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    card_id bigint
);


--
-- Name: ledger_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ledger_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ledger_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ledger_entries (
    id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    entry_type character varying(255),
    reference character varying(255),
    ledger_account_id bigint NOT NULL,
    CONSTRAINT ledger_entries_entry_type_check CHECK (((entry_type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[])))
);


--
-- Name: ledger_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ledger_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbound_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbound_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    attempts integer NOT NULL,
    business_ref character varying(120),
    card_id bigint,
    channel character varying(20) NOT NULL,
    customer_id bigint,
    last_error character varying(480),
    provider_mode character varying(20),
    provider_ref character varying(120),
    recipient character varying(160) NOT NULL,
    sent_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    template character varying(40) NOT NULL,
    text text,
    CONSTRAINT outbound_messages_channel_check CHECK (((channel)::text = ANY ((ARRAY['SMS'::character varying, 'WHATSAPP'::character varying, 'EMAIL'::character varying])::text[]))),
    CONSTRAINT outbound_messages_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'SENT'::character varying, 'DELIVERED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: outbound_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outbound_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbound_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plastic_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plastic_batches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    algorithm character varying(32),
    batch_number character varying(32) NOT NULL,
    built_by character varying(80),
    encrypted_file bytea,
    failed_count integer NOT NULL,
    iv character varying(32),
    manufacturer character varying(80) NOT NULL,
    produced_at timestamp(6) without time zone,
    record_count integer NOT NULL,
    sent_at timestamp(6) without time zone,
    sha256plain character varying(64),
    status character varying(12) NOT NULL,
    CONSTRAINT plastic_batches_status_check CHECK (((status)::text = ANY ((ARRAY['BUILT'::character varying, 'SENT'::character varying, 'PRODUCED'::character varying])::text[])))
);


--
-- Name: plastic_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plastic_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plastic_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plastics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plastics (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    activated_at timestamp(6) without time zone,
    batched_at timestamp(6) without time zone,
    carrier character varying(40),
    chip_profile character varying(40),
    closed_at timestamp(6) without time zone,
    delivered_at timestamp(6) without time zone,
    delivery_address character varying(500),
    embossed_name character varying(26),
    expiry date,
    note character varying(500),
    pin_mailer boolean NOT NULL,
    produced_at timestamp(6) without time zone,
    reason character varying(24) NOT NULL,
    requested_by character varying(80),
    sent_at timestamp(6) without time zone,
    sequence integer NOT NULL,
    shipped_at timestamp(6) without time zone,
    status character varying(24) NOT NULL,
    tracking_number character varying(80),
    batch_id bigint,
    card_id bigint NOT NULL,
    CONSTRAINT plastics_reason_check CHECK (((reason)::text = ANY ((ARRAY['NEW'::character varying, 'REPLACEMENT_LOST'::character varying, 'REPLACEMENT_STOLEN'::character varying, 'REPLACEMENT_DAMAGED'::character varying, 'RENEWAL'::character varying])::text[]))),
    CONSTRAINT plastics_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'IN_BATCH'::character varying, 'SENT_TO_MANUFACTURER'::character varying, 'PRODUCED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'ACTIVATED'::character varying, 'RETURNED'::character varying, 'DESTROYED'::character varying])::text[])))
);


--
-- Name: plastics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plastics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plastics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promotions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    cashback_percentage numeric(5,2),
    description character varying(255),
    discount_percentage numeric(5,2),
    end_date character varying(255),
    max_benefit_cap numeric(19,2),
    merchant_category character varying(255),
    min_purchase_amount numeric(19,2),
    name character varying(255) NOT NULL,
    promotion_type character varying(255),
    start_date character varying(255),
    target_product_id bigint
);


--
-- Name: promotions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reconciliation_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reconciliation_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    account_id character varying(80) NOT NULL,
    approval_code character varying(40),
    card_id bigint,
    cms_amount numeric(19,2),
    core_amount numeric(19,2),
    core_ref character varying(80),
    detail character varying(500),
    item_key character varying(200) NOT NULL,
    last_seen_at timestamp(6) without time zone,
    resolution character varying(300),
    resolved_at timestamp(6) without time zone,
    status character varying(16) NOT NULL,
    type character varying(32) NOT NULL,
    CONSTRAINT reconciliation_items_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying])::text[]))),
    CONSTRAINT reconciliation_items_type_check CHECK (((type)::text = ANY ((ARRAY['HOLD_MISSING_IN_CORE'::character varying, 'CAPTURE_MISSING_IN_CORE'::character varying, 'AMOUNT_MISMATCH'::character varying, 'HOLD_NOT_RELEASED'::character varying, 'UNKNOWN_CORE_DEBIT'::character varying, 'HOLD_TOTAL_MISMATCH'::character varying, 'STAND_IN_REJECTED'::character varying, 'CLEARING_NO_AUTHORIZATION'::character varying, 'CLEARING_AMOUNT_MISMATCH'::character varying, 'CLEARING_DUPLICATE'::character varying, 'CLEARING_NO_CARD'::character varying, 'CLEARING_UNMATCHED'::character varying])::text[])))
);


--
-- Name: reconciliation_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reconciliation_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reconciliation_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_runs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    csv text,
    format character varying(10) NOT NULL,
    generated_by character varying(80),
    params character varying(400),
    period_from date,
    period_to date,
    report_code character varying(40) NOT NULL,
    row_count integer NOT NULL,
    sha256 character varying(64) NOT NULL,
    title character varying(120) NOT NULL
);


--
-- Name: report_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_cycles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_cycles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    batch_count integer NOT NULL,
    chargebacks_amount numeric(19,2) NOT NULL,
    closed_at timestamp(6) without time zone,
    closed_by character varying(80),
    currency character varying(3),
    cycle_date date NOT NULL,
    exception_count integer NOT NULL,
    fees_amount numeric(19,2),
    interchange_amount numeric(19,2) NOT NULL,
    net_position numeric(19,2) NOT NULL,
    network character varying(20) NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_ref character varying(80),
    presentments_amount numeric(19,2) NOT NULL,
    presentments_count integer NOT NULL,
    reversals_amount numeric(19,2) NOT NULL,
    settlement_file text,
    sha256 character varying(64),
    status character varying(10) NOT NULL,
    CONSTRAINT settlement_cycles_network_check CHECK (((network)::text = ANY ((ARRAY['VISA'::character varying, 'MASTERCARD'::character varying, 'DOMESTIC'::character varying])::text[]))),
    CONSTRAINT settlement_cycles_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying, 'PAID'::character varying])::text[])))
);


--
-- Name: settlement_cycles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_cycles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_cycles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: step_up_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.step_up_challenges (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19,2) NOT NULL,
    attempts integer NOT NULL,
    channel character varying(20),
    expires_at timestamp(6) without time zone,
    merchant_id character varying(50),
    otp character varying(12) NOT NULL,
    status character varying(12) NOT NULL,
    token character varying(80) NOT NULL,
    card_id bigint NOT NULL,
    CONSTRAINT step_up_challenges_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'CONSUMED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: step_up_challenges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.step_up_challenges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.step_up_challenges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: third_party_contracts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.third_party_contracts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    checklist text,
    contact character varying(200),
    contract_ref character varying(80),
    expires_at date,
    provider_key character varying(40) NOT NULL,
    signed_at date,
    sla_notes text,
    status character varying(20) NOT NULL,
    updated_by character varying(80),
    vendor character varying(160),
    CONSTRAINT third_party_contracts_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'NEGOTIATION'::character varying, 'SIGNED'::character varying, 'CERTIFYING'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'TERMINATED'::character varying])::text[])))
);


--
-- Name: third_party_contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.third_party_contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.third_party_contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: authorization_attempts authorization_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authorization_attempts
    ADD CONSTRAINT authorization_attempts_pkey PRIMARY KEY (id);


--
-- Name: authorization_holds authorization_holds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authorization_holds
    ADD CONSTRAINT authorization_holds_pkey PRIMARY KEY (id);


--
-- Name: card_controls card_controls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_controls
    ADD CONSTRAINT card_controls_pkey PRIMARY KEY (id);


--
-- Name: card_products card_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_products
    ADD CONSTRAINT card_products_pkey PRIMARY KEY (id);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: clearing_batches clearing_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearing_batches
    ADD CONSTRAINT clearing_batches_pkey PRIMARY KEY (id);


--
-- Name: clearing_records clearing_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearing_records
    ADD CONSTRAINT clearing_records_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: dispute_events dispute_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_events
    ADD CONSTRAINT dispute_events_pkey PRIMARY KEY (id);


--
-- Name: dispute_evidences dispute_evidences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_evidences
    ADD CONSTRAINT dispute_evidences_pkey PRIMARY KEY (id);


--
-- Name: dispute_reasons dispute_reasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_reasons
    ADD CONSTRAINT dispute_reasons_pkey PRIMARY KEY (id);


--
-- Name: disputes disputes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_pkey PRIMARY KEY (id);


--
-- Name: fraud_alerts fraud_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fraud_alerts_pkey PRIMARY KEY (id);


--
-- Name: fraud_blocklist fraud_blocklist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_blocklist
    ADD CONSTRAINT fraud_blocklist_pkey PRIMARY KEY (id);


--
-- Name: guild_alerts guild_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_alerts
    ADD CONSTRAINT guild_alerts_pkey PRIMARY KEY (id);


--
-- Name: guild_verifications guild_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_verifications
    ADD CONSTRAINT guild_verifications_pkey PRIMARY KEY (id);


--
-- Name: idempotency_records idempotency_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT idempotency_records_pkey PRIMARY KEY (id);


--
-- Name: plastic_batches ix_batch_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plastic_batches
    ADD CONSTRAINT ix_batch_number UNIQUE (batch_number);


--
-- Name: step_up_challenges ix_challenge_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_up_challenges
    ADD CONSTRAINT ix_challenge_token UNIQUE (token);


--
-- Name: guild_verifications ix_guild_verif_subject; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_verifications
    ADD CONSTRAINT ix_guild_verif_subject UNIQUE (subject_type, subject);


--
-- Name: reconciliation_items ix_recon_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reconciliation_items
    ADD CONSTRAINT ix_recon_key UNIQUE (item_key);


--
-- Name: settlement_cycles ix_settlement_cycle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_cycles
    ADD CONSTRAINT ix_settlement_cycle UNIQUE (network, cycle_date);


--
-- Name: kyc_documents kyc_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc_documents
    ADD CONSTRAINT kyc_documents_pkey PRIMARY KEY (id);


--
-- Name: kyc kyc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT kyc_pkey PRIMARY KEY (id);


--
-- Name: ledger_accounts ledger_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_accounts
    ADD CONSTRAINT ledger_accounts_pkey PRIMARY KEY (id);


--
-- Name: ledger_entries ledger_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT ledger_entries_pkey PRIMARY KEY (id);


--
-- Name: outbound_messages outbound_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbound_messages
    ADD CONSTRAINT outbound_messages_pkey PRIMARY KEY (id);


--
-- Name: plastic_batches plastic_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plastic_batches
    ADD CONSTRAINT plastic_batches_pkey PRIMARY KEY (id);


--
-- Name: plastics plastics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plastics
    ADD CONSTRAINT plastics_pkey PRIMARY KEY (id);


--
-- Name: promotions promotions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);


--
-- Name: reconciliation_items reconciliation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reconciliation_items
    ADD CONSTRAINT reconciliation_items_pkey PRIMARY KEY (id);


--
-- Name: report_runs report_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_runs
    ADD CONSTRAINT report_runs_pkey PRIMARY KEY (id);


--
-- Name: settlement_cycles settlement_cycles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_cycles
    ADD CONSTRAINT settlement_cycles_pkey PRIMARY KEY (id);


--
-- Name: step_up_challenges step_up_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_up_challenges
    ADD CONSTRAINT step_up_challenges_pkey PRIMARY KEY (id);


--
-- Name: third_party_contracts third_party_contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.third_party_contracts
    ADD CONSTRAINT third_party_contracts_pkey PRIMARY KEY (id);


--
-- Name: dispute_reasons uk2pwueo8td5oh05d72cb8n4nj2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_reasons
    ADD CONSTRAINT uk2pwueo8td5oh05d72cb8n4nj2 UNIQUE (code);


--
-- Name: ledger_accounts uk37h4pwl7i4ke8ftpjdh599rdd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_accounts
    ADD CONSTRAINT uk37h4pwl7i4ke8ftpjdh599rdd UNIQUE (card_id);


--
-- Name: kyc uk5plosanxn2vawddmmc5fkha07; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT uk5plosanxn2vawddmmc5fkha07 UNIQUE (customer_id);


--
-- Name: fraud_blocklist uk_block_type_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_blocklist
    ADD CONSTRAINT uk_block_type_value UNIQUE (type, value);


--
-- Name: card_controls ukc5m142pdas0itbg37ux905uii; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_controls
    ADD CONSTRAINT ukc5m142pdas0itbg37ux905uii UNIQUE (card_id);


--
-- Name: card_products ukc5ywsluoo47yuxh6t1ls9oixb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_products
    ADD CONSTRAINT ukc5ywsluoo47yuxh6t1ls9oixb UNIQUE (product_code);


--
-- Name: idempotency_records ukol0gjg0uap11mq1y9ug506f1i; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT ukol0gjg0uap11mq1y9ug506f1i UNIQUE (idempotency_key);


--
-- Name: authorization_holds ukqiocu3f2hcs88yw9w43t68atv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authorization_holds
    ADD CONSTRAINT ukqiocu3f2hcs88yw9w43t68atv UNIQUE (approval_code);


--
-- Name: third_party_contracts ux_third_party_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.third_party_contracts
    ADD CONSTRAINT ux_third_party_key UNIQUE (provider_key);


--
-- Name: ix_alert_merchant_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_merchant_at ON public.fraud_alerts USING btree (merchant_id, created_at);


--
-- Name: ix_alert_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_alert_status ON public.fraud_alerts USING btree (status);


--
-- Name: ix_attempt_card_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_attempt_card_at ON public.authorization_attempts USING btree (card_id, created_at);


--
-- Name: ix_attempt_merchant_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_attempt_merchant_at ON public.authorization_attempts USING btree (merchant_id, created_at);


--
-- Name: ix_clearing_batch_cycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_clearing_batch_cycle ON public.clearing_batches USING btree (network, cycle_date);


--
-- Name: ix_clearing_rec_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_clearing_rec_batch ON public.clearing_records USING btree (batch_id);


--
-- Name: ix_clearing_rec_outcome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_clearing_rec_outcome ON public.clearing_records USING btree (outcome);


--
-- Name: ix_clearing_rec_rrn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_clearing_rec_rrn ON public.clearing_records USING btree (rrn);


--
-- Name: ix_dispute_approval; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_dispute_approval ON public.disputes USING btree (approval_code);


--
-- Name: ix_dispute_card; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_dispute_card ON public.disputes USING btree (card_id);


--
-- Name: ix_dispute_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_dispute_status ON public.disputes USING btree (status);


--
-- Name: ix_event_dispute; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_event_dispute ON public.dispute_events USING btree (dispute_id);


--
-- Name: ix_evidence_dispute; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_evidence_dispute ON public.dispute_evidences USING btree (dispute_id);


--
-- Name: ix_guild_alerts_card; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_guild_alerts_card ON public.guild_alerts USING btree (card_id);


--
-- Name: ix_guild_alerts_folio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_guild_alerts_folio ON public.guild_alerts USING btree (guild_folio);


--
-- Name: ix_guild_alerts_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_guild_alerts_status ON public.guild_alerts USING btree (status);


--
-- Name: ix_hold_card_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_hold_card_created ON public.authorization_holds USING btree (card_id, created_at);


--
-- Name: ix_hold_card_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_hold_card_status ON public.authorization_holds USING btree (card_id, status);


--
-- Name: ix_outbound_msg_card; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_outbound_msg_card ON public.outbound_messages USING btree (card_id);


--
-- Name: ix_outbound_msg_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_outbound_msg_status ON public.outbound_messages USING btree (status, created_at);


--
-- Name: ix_plastic_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_plastic_batch ON public.plastics USING btree (batch_id);


--
-- Name: ix_plastic_card_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_plastic_card_status ON public.plastics USING btree (card_id, status);


--
-- Name: ix_recon_account_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_recon_account_status ON public.reconciliation_items USING btree (account_id, status);


--
-- Name: ix_report_runs_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_report_runs_code ON public.report_runs USING btree (report_code);


--
-- Name: ix_report_runs_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_report_runs_created ON public.report_runs USING btree (created_at);


--
-- Name: audit_logs trg_audit_logs_no_modify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_logs_no_modify BEFORE DELETE OR UPDATE ON public.audit_logs FOR EACH STATEMENT EXECUTE FUNCTION public.audit_logs_no_modify();


--
-- Name: authorization_attempts fk12jw2hjhrt75n0ndu4su7arui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authorization_attempts
    ADD CONSTRAINT fk12jw2hjhrt75n0ndu4su7arui FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: kyc_documents fk2f6vyhypfnmdg9wii1y9js6nf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc_documents
    ADD CONSTRAINT fk2f6vyhypfnmdg9wii1y9js6nf FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: kyc fk2qhciw6flmi7mamir7g88jv0q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT fk2qhciw6flmi7mamir7g88jv0q FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: authorization_holds fk33ox5ecqsnxdicpyw82l6torv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authorization_holds
    ADD CONSTRAINT fk33ox5ecqsnxdicpyw82l6torv FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: plastics fk37ie3h1mhsv3e4xftucv266r6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plastics
    ADD CONSTRAINT fk37ie3h1mhsv3e4xftucv266r6 FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: cards fk3ta7cnyyuv26sr3j2sxrr10bu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT fk3ta7cnyyuv26sr3j2sxrr10bu FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: card_controls fk75ugvatl4iouve8x5m9cd17et; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_controls
    ADD CONSTRAINT fk75ugvatl4iouve8x5m9cd17et FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: dispute_events fk8akfdmncxtbp88u240fuhstdi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_events
    ADD CONSTRAINT fk8akfdmncxtbp88u240fuhstdi FOREIGN KEY (dispute_id) REFERENCES public.disputes(id);


--
-- Name: disputes fk9rt47dqxfd28pcpqyciyvd58h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT fk9rt47dqxfd28pcpqyciyvd58h FOREIGN KEY (hold_id) REFERENCES public.authorization_holds(id);


--
-- Name: ledger_accounts fke4xcvckj324bax71ttp6oxg53; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_accounts
    ADD CONSTRAINT fke4xcvckj324bax71ttp6oxg53 FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: dispute_evidences fkeql9nopjw2kunnxc1h6qshxfn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_evidences
    ADD CONSTRAINT fkeql9nopjw2kunnxc1h6qshxfn FOREIGN KEY (dispute_id) REFERENCES public.disputes(id);


--
-- Name: clearing_records fkkrl9i09999phtlnv5smnh0g1r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearing_records
    ADD CONSTRAINT fkkrl9i09999phtlnv5smnh0g1r FOREIGN KEY (batch_id) REFERENCES public.clearing_batches(id);


--
-- Name: fraud_alerts fkni8nwhv6kis1tn60un222wrjo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fkni8nwhv6kis1tn60un222wrjo FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: step_up_challenges fkodm2hdqh8rpfnr6cv6dym9l7n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_up_challenges
    ADD CONSTRAINT fkodm2hdqh8rpfnr6cv6dym9l7n FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: disputes fkorvwuyf9y252425m9g32vi9xi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT fkorvwuyf9y252425m9g32vi9xi FOREIGN KEY (card_id) REFERENCES public.cards(id);


--
-- Name: ledger_entries fkqi8wlbn38b78ymja316edpkgg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT fkqi8wlbn38b78ymja316edpkgg FOREIGN KEY (ledger_account_id) REFERENCES public.ledger_accounts(id);


--
-- Name: cards fksbaj8n1nqok3b5lllwcxy43ip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT fksbaj8n1nqok3b5lllwcxy43ip FOREIGN KEY (product_id) REFERENCES public.card_products(id);


--
-- Name: plastics fksgnh589tcygtmc821jm8l26uv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plastics
    ADD CONSTRAINT fksgnh589tcygtmc821jm8l26uv FOREIGN KEY (batch_id) REFERENCES public.plastic_batches(id);


--
-- Name: promotions fktj5yhbx35inc5x9x2slnx5sdp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT fktj5yhbx35inc5x9x2slnx5sdp FOREIGN KEY (target_product_id) REFERENCES public.card_products(id);


--
-- Name: disputes fkxsnd28hda0culao5f2o420yj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT fkxsnd28hda0culao5f2o420yj FOREIGN KEY (reason_id) REFERENCES public.dispute_reasons(id);


--
-- PostgreSQL database dump complete
--


